language: r
cache: 
  packages: true
r:
  - release
r_packages:
  - covr

warnings_are_errors: false
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
before_deploy: Rscript -e "install.packages(c('devtools'))" && Rscript -e "library('devtools')" -e "library('pkgdown')" -e "devtools::build(binary = TRUE, args = c('--preclean'))" && Rscript -e "devtools::document()" -e "pkgdown::build_site()"
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

after_success:
  - Rscript -e 'library(covr); codecov()'

