# The suggested name for this image is: do1-aps-feris.isas.de:5000/isas/suprg-base

FROM rocker/tidyverse:3.6.2

MAINTAINER nils.hoffmann@isas.de

ADD install.R /tmp/
# invalidates cache every 24 hours
ADD http://master.bioconductor.org/todays-date /tmp/
#need to install the packages globally
RUN R -f /tmp/install.R

ADD install-custom.R /tmp/
RUN R -f /tmp/install-custom.R
